### ISSUE TITLE
Error loading in routes

### ISSUE THREAD

**Issue by g7uvw** [jonocarroll/runkeepR#6]
Hello,

I'm very very new to R, but have managed to get this package installed. Trying to load in routes just errors.

```
> getwd()
[1] "/Users/dm/scratch/runkeeper"
> library(runkeepR)
routes <- load_tracks(".")
Error in class(xx) <- cl : attempt to set an attribute on NULL
```

That's as far as I get, the files definitely exist at the location and there are no permission issues there. Makes no difference if I give the full path name to load_tracks either.

Is there an issue with the package, or do I need to learn a lot more R before I can use it?

**Comment by jonocarroll** [comment]
Hi, thanks for the report. I haven't touched this code for a very long time so it's probably broken. I will have a look at repairing it.

**Comment by g7uvw** [comment]
Thank you for taking a look. I'm well in over my head here.

**Comment by jonocarroll** [comment]
Please let me know if this resolves it for you - it seemed to be some odd Windows-specific issue because the tests passed just fine on my machine.

**Comment by g7uvw** [comment]
Perfect! Thank you.
